#########################
#                       #
# Coded by KieranSlayer #
#                       #
#########################

#Color codes work with & so if u know the color u want just use & in front of it#

#Please do not remove '' As that will break the plugin #

#If broken contact me or redo config #
Hello: '&6Hello and Welcome to &2SERVERNAME'